feed/urls.py
from . import views
from django.urls import path
from .views import feed


urlpatterns = [
    path('feed/', feed, name='feed'),
]

litreview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('posts.urls')),
    path('', include('user_profile.urls')),
    path('', include('subscriptions.urls')),
    path('', include('feed.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import posts, create_ticket, create_review, \
    create_ticket_and_review, edit_ticket, edit_review

app_name = "posts"
urlpatterns = [
    path('', posts, name='home'),
    path('create-ticket/', create_ticket, name='create_ticket'),
    path('create-review/', create_ticket_and_review, name='create_ticket_and_review'),
    path('create-review/<int:ticket_id>/', create_review, name='create_review'),
    path('edit-ticket/<int:ticket_id>/', edit_ticket, name='edit_ticket'),
    path('edit-ticket/<int:ticket_id>/', edit_ticket, name='delete_ticket'),
    path('edit-review/<int:review_id>/', edit_review, name='edit_review'),
    path('delete-review/<int:review_id>/', edit_review, name='delete_review'),
]

templates/base.html
{% load static %}
<html>

<head>
    <title>LitReviews</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://kit.fontawesome.com/8e873955b8.js" crossorigin="anonymous"></script>
</head>

<body>
    <header>
        <div class="header">
            <p><a href="{% url 'posts:home' %}">LITReview</a></p>
            {%if user.is_authenticated %}
            <nav class="navigation">
                <ul>
                    <li><a href="{% url 'feed' %}">Feed</a></li>
                    </li>
                    <li><a href="{% url 'posts:home' %}">Posts</a></li>
                    </li>
                    <li><a href="{% url 'follows'  %}">Abonnements</a></li>
                    </li>
                    <li><a href="{% url 'logout' %}">Me déconnecter</a></li>
                    <li><a href="{% url 'user_profile' request.user %}">Mon Profil</a></li>
                </ul>
            </nav>
            {% endif %}
        </div>
    </header>

    <div class="container" style="flex-direction: column;">
        {% block content %}{% endblock content %}
    </div>

</body>

</html>