feed/urls.py
from . import views
from django.urls import path
from .views import feed


urlpatterns = [
    path('feed/', feed, name='feed'),
]

litreview/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('posts.urls')),
    path('', include('user_profile.urls')),
    path('', include('subscriptions.urls')),
    path('', include('feed.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import posts, create_ticket, create_review, \
    create_ticket_and_review, edit_ticket, edit_review

app_name = "posts"
urlpatterns = [
    path('', posts, name='home'),
    path('create-ticket/', create_ticket, name='create_ticket'),
    path('create-review/', create_ticket_and_review, name='create_ticket_and_review'),
    path('create-review/<int:ticket_id>/', create_review, name='create_review'),
    path('edit-ticket/<int:ticket_id>/', edit_ticket, name='edit_ticket'),
    path('edit-ticket/<int:ticket_id>/', edit_ticket, name='delete_ticket'),
    path('edit-review/<int:review_id>/', edit_review, name='edit_review'),
    path('delete-review/<int:review_id>/', edit_review, name='delete_review'),
]

posts/models.py
from django.db import models

# Create your models here.
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings


class Ticket(models.Model):
    # Your Ticket model definition goes here
    pass
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=2048, blank=True)
    image = models.ImageField(blank=True, null=True)
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Review(models.Model):
    ticket = models.ForeignKey(to=Ticket, related_name='reviews', on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        # validates that rating must be between 0 and 5
        validators=[MinValueValidator(0), MaxValueValidator(5)])
    headline = models.CharField(max_length=128)
    body = models.CharField(max_length=8192, blank=True)
    user = models.ForeignKey(
        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    time_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.headline

posts/forms.py
from django import forms
from . import models


class TicketForm(forms.ModelForm):
    edit_ticket = forms.BooleanField(widget=forms.HiddenInput, initial=True)

    class Meta:
        model = models.Ticket
        fields = ['title', 'description', 'image']


class TicketFormDelete(forms.Form):
    delete_ticket = forms.BooleanField(widget=forms.HiddenInput, initial=True)


class ReviewForm(forms.ModelForm):
    edit_review = forms.BooleanField(widget=forms.HiddenInput, initial=True)

    class Meta:
        model = models.Review
        fields = ['headline', 'body', 'rating']


class ReviewFormDelete(forms.Form):
    delete_review = forms.BooleanField(widget=forms.HiddenInput, initial=True)

posts/views.py
import numpy as np

from django.shortcuts import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required

from .models import Ticket, Review
from . import forms


# Create your views here.
@login_required(login_url='login/')
def posts(request):
    template_name = 'posts/index.html'
    all_tickets = []

    if not request.user.is_authenticated:
        return HttpResponseRedirect('login') # or http response
    else:
        tickets = Ticket.objects.filter(user=request.user)
        all_reviews = Review.objects.filter(user=request.user)
        for ticket in tickets:
            reviews = ticket.reviews.all()
            all_tickets.append({"ticket": ticket, "reviews": list(reviews)})

        items = np.concatenate((tickets, list(reviews), list(all_reviews)))
        items_sorted = sorted(items, key=lambda item: item.time_created, reverse=True)

        context = {
            'tickets': all_tickets,
            'items': items_sorted,
        }

        return render(
            request,
            template_name,
            context
        )


@login_required(login_url='login/')
def create_ticket(request):
    form = forms.TicketForm()
    if request.method == 'POST':
        form = forms.TicketForm(request.POST, request.FILES)
        if form.is_valid():
            ticket = form.save(commit=False)
            ticket.user = request.user
            if form.cleaned_data['image']:
                ticket.image = form.cleaned_data['image']
            ticket.save()
            return redirect('posts:home')
    context = {
        'form': form
    }
    return render(
        request,
        'posts/create_ticket.html',
        context
    )


@login_required(login_url='login/')
def create_review(request, ticket_id):
    form = forms.ReviewForm()
    if request.method == 'POST':
        form = forms.ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.ticket = get_object_or_404(Ticket, id=ticket_id)
            review.ticket.has_review = True
            review.ticket.save()
            review.save()
            return redirect('posts:home')
    context = {
        'both': False,
        'form': form,
        'ticket': get_object_or_404(Ticket, id=ticket_id)
    }
    return render(
        request,
        'posts/create_review.html',
        context
    )


def create_ticket_and_review(request):
    ticket_form = forms.TicketForm()
    review_form = forms.ReviewForm()
    if request.method == 'POST':
        ticket_form = forms.TicketForm(request.POST, request.FILES)
        review_form = forms.ReviewForm(request.POST)
        if all([ticket_form.is_valid(), review_form.is_valid()]):
            ticket = ticket_form.save(commit=False)
            ticket.user = request.user
            if ticket_form.cleaned_data['image']:
                ticket.image = ticket_form.cleaned_data['image']
            ticket.has_review = True
            ticket.save()
            review = review_form.save(commit=False)
            review.user = request.user
            review.ticket = get_object_or_404(Ticket, id=ticket.id)
            review.save()
            return redirect('posts:home')
    context = {
        'both': True,
        'ticket_form': ticket_form,
        'review_form': review_form,
    }
    return render(
        request,
        'posts/create_review.html',
        context
    )


@login_required(login_url='login/')
def edit_ticket(request, ticket_id):
    ticket = get_object_or_404(Ticket, id=ticket_id)
    edit_form = forms.TicketForm(instance=ticket)
    delete_form = forms.TicketFormDelete()
    if request.method == 'POST':
        if 'edit_ticket' in request.POST:
            edit_form = forms.TicketForm(request.POST, instance=ticket)
            if edit_form.is_valid():
                edit_form.save()
                return redirect('posts:home')
        if 'delete_ticket' in request.POST:
            delete_form = forms.TicketFormDelete(request.POST)
            if delete_form.is_valid():
                ticket.delete()
                return redirect('posts:home')
    context = {
        'edit_form': edit_form,
        'delete_form': delete_form
    }
    return render(
        request,
        'posts/edit_ticket.html',
        context
    )


@login_required(login_url='login/')
def edit_review(request, review_id):
    review = get_object_or_404(Review, id=review_id)
    edit_form = forms.ReviewForm(instance=review)
    delete_form = forms.ReviewFormDelete()
    if request.method == 'POST':
        if 'edit_review' in request.POST:
            edit_form = forms.ReviewForm(request.POST, instance=review)
            if edit_form.is_valid():
                edit_form.save()
                return redirect('posts:home')
        if 'delete_review' in request.POST:
            delete_form = forms.ReviewFormDelete(request.POST)
            if delete_form.is_valid():
                review.delete()
                return redirect('posts:home')
    context = {
        'edit_form': edit_form,
        'delete_form': delete_form
    }
    return render(
        request,
        'posts/edit_review.html',
        context
    )

posts/templates/posts/create_review.html
{% extends 'base.html' %}

{% block content %}
<div class="form form__review">
    <h2>Créer une critique</h2>
    {% if both %}
    <form method="post" enctype="multipart/form-data" style="width: 80%;">
        <h4>A propos de ce livre:</h4>
        {{ ticket_form.as_p }}
        <h4>Critique</h4>
        {{ review_form.as_p }}
        {% csrf_token %}
        <input class="btn" type="submit" value="Envoyer" style="width: auto; height: auto;">
    </form>
    {% else %}
    <div style="width: 100%; padding: 1rem">
        <p style="align-self: flex-start;">Vous êtes en train de poster une critique</p>
        <div style="display: flex;">
            {% include 'posts/partials/ticket.html' with item=ticket %}
        </div>

    </div>

    <form method="post" style="width: 100%; border: 1px solid #000; padding: 1rem">
        {{ form.as_p }}
        {% csrf_token %}
        <input class="btn" type="submit" value="Envoyer" style="width: auto; height: auto;">
    </form>
    {% endif %}
</div>
{% endblock content %}

posts/templates/posts/create_ticket.html
{% extends 'base.html' %}

{% block content %}
<div class="form form__ticket">
    <h2>Créer un Ticket</h2>
    <form method="post" enctype="multipart/form-data" style="width: 80%;">
        {{ form.as_p }}
        {% csrf_token %}
        <input style="width: auto; height: auto;" class="btn" type="submit" value="Envoyer">
    </form>
</div>
{% endblock content %}

posts/templates/posts/edit_page.html
{% extends 'base.html' %}
{% block content %}
<div class="form form__review">
    <h2>Modifier la critique</h2>
    <form method="post" style="width: 80%;">
        {{ edit_form.as_p }}
        {% csrf_token %}
        <button class="btn" type="submit">Sauvegarder</button>
    </form>
    <hr>
    <h3>Supprimer la critique ?</h3>
    <form method="post" style="width: 80%;">
        {{ delete_form }}
        {% csrf_token %}
        <a class="btn" href="{% url 'posts:home' %}">Annnuler</a>
        <button class="btn" type="submit">Supprimer</button>
    </form>
</div>
{% endblock content %}

posts/templates/posts/edit_review.html
{% extends 'base.html' %}
{% block content %}
<div class="form form__review">
    <h2>Modifier la critique</h2>
    <form method="post" style="width: 80%;">
        {{ edit_form.as_p }}
        {% csrf_token %}
        <button class="btn" type="submit">Sauvegarder</button>
    </form>
    <hr>
    <h3>Supprimer la critique ?</h3>
    <form method="post" style="width: 80%;">
        {{ delete_form }}
        {% csrf_token %}
        <a class="btn" href="{% url 'posts:home' %}">Annnuler</a>
        <button class="btn" type="submit">Supprimer</button>
    </form>
</div>
{% endblock content %}

posts/templates/posts/edit_ticket.html
{% extends 'base.html' %}
{% block content %}
<div class="form form__ticket">
    <h2>Modifier le ticket</h2>
    <form method="post" style="width: 80%;">
        {{ edit_form.as_p }}
        {% csrf_token %}
        <button class="btn" type="submit">Sauvegarder</button>
    </form>
    <hr />
    <h3>Supprimer le ticket ?</h3>
    <form method="post" style="width: 80%;">
        {{ delete_form }}
        {% csrf_token %}
        <button class="btn" type="submit">Supprimer</button>
        <a class="btn" href="{% url 'posts:home' %}">Annuler</a>
    </form>
</div>
{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}

<div class="home">
    <a class="btn mr-5" href="{% url 'posts:create_ticket' %}">Demander une critique</a>
    <a class="btn" href="{% url 'posts:create_ticket_and_review' %}">Créer une critique</a>
</div>

<div style="display: flex; align-items: center; flex-direction: column;">
    {% for item in items %}
    {% include 'posts/partials/ticket.html' with item=item %}
    {% endfor %}
</div>

</div>
{% endblock content %}